services:
   - type: web
    name: ragaas-ui
    env: static
    staticPublishPath: frontend/dist
    buildCommand: npm install && npm run build
    startCommand: serve frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18
    plan: free
 
