services:
  - type: web
    name: ragaas-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
    plan: free
    autoDeploy: true

  - type: web
    name: ragaas-ui
    env: static
    staticPublishPath: frontend/dist
    buildCommand: npm install && npm run build
    envVars:
      - key: NODE_VERSION
        value: 18
    plan:
